version: '3.9'

services:
  backend:
    image: geoassets-backend
    build:
      context: ./geoassets-server-main
    networks:
      - creinnova-network
    ports:
      - "3000:3000"
    environment: 
      - PORT=3000
      - MONGODB_URI=${MONGODB_URI}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - API_VERSION=${API_VERSION}
      - IP_SERVER=${IP_SERVER}
      - ALLOWED_ORIGIN=${ALLOWED_ORIGIN}

  frontend:
    image: geoassets-frontend
    build:
      context: ./geoassets-client-main
    ports:
      - "5173:80"   # mapea el puerto del Nginx
    networks:
      - creinnova-network
    depends_on:
      - backend
      

networks:
  creinnova-network:
    driver: bridge
