version: '3.9'

services:
  backend:
    image: geoassets-backend
    build:
      context: ./geoassets-server-main
    networks:
      - creinnova-network
    ports:
      - "3000:3000"
    environment: 
      - PORT=${PORT}
      - IP_SERVER=${IP_SERVER}
      - API_VERSION=${API_VERSION}
      - ALLOWED_ORIGIN=${ALLOWED_ORIGIN}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}

  frontend:
    image: geoassets-frontend
    build:
      context: ./geoassets-client-main
    ports:
      - "5173:80"   # mapea el puerto del Nginx
    networks:
      - creinnova-network
    depends_on:
      - backend

networks:
  creinnova-network:
    driver: bridge